- name: Install MySQL
  ansible.builtin.apt:
    name: default-mysql-server
    state: present
  become: yes
  tags:
    - mysql
    - installation

- name: Install MySQLDB Python Library
  ansible.builtin.apt:
    name: python3-mysqldb
    state: present
  become: yes
  tags:
    - mysql
    - python-mysql
    - installation

- name: Create Staging Database
  mysql_db:
    name: "{{ staging_db_name }}"
    state: present
  become: yes
  tags:
    - mysql
    - db
    - staging

- name: Create Staging MySQL User
  mysql_user:
    name: "{{ stag_user }}"
    password: "{{ mysql_stag_pass }}"
    priv: '*.*:ALL'
    host: '%'
    state: present
  become: yes
  tags:
    - db
    - db_user
    - staging
  vars:
    column_case_sensitive: false

- name: Create Production Database
  mysql_db:
    name: "{{ my_production_db }}"
    state: present
  become: yes
  tags:
    - mysql
    - db
    - production
  
- name: Create Production MySQL User
  mysql_user:
    name: "{{ my_production_user }}"
    password: "{{ mysql_prod_pass }}"
    priv: '*.*:ALL'
    host: '%'
    state: present
  become: yes
  tags:
    - mysql
    - db
    - db_user
    - production
  notify:
    - restart_mysql
  vars:
    column_case_sensitive: false
