- name: restart_nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: yes

- name: restart_php-fpm
  ansible.builtin.service:
    name: php8.2-fpm
    state: restarted
  become: yes

- name: restart_mysql
  ansible.builtin.service:
    name: mysql
    state: restarted
  become: yes
    
