all:
  hosts:
    stag-web-server:
      ansible_host: 162.19.124.210
      ansible_user: debian
    prod-web-server:
      ansible_host: 141.95.167.27
      ansible_user: debian

  children:
    webservers:  
      hosts:
        stag-web-server:
        prod-web-server:

    dbservers:
      hosts:
        stag-web-server:
        prod-web-server:

    staging:
      hosts:
        stag-web-server:

    production:
      hosts:
        prod-web-server:
